package:
  name: autocnet-dev
  version: 0.1.0
channels:
  - conda-forge
source:
   git_url: https://github.com/USGS-Astrogeology/autocnet.git
   #path: ../
requirements:
  build:
    - python=3
    - vlfeat
    - cyvlfeat
    - pillow
    - scipy
    - networkx
    - numexpr
    - cython
    - matplotlib
    - geopandas
    - opencv3
    - numpy
    - plio
    - gdal
  run:
    - python=3
    - vlfeat
    - cyvlfeat
    - pillow
    - scipy
    - networkx
    - numexpr
    - cython
    - matplotlib
    - geopandas
    - opencv3
    - numpy
    - plio
    - gdal

test:
  imports:
    - autocnet
    - autocnet.graph.network
